

spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amathon_db?useSSL=false&characterEncoding=utf8
  profiles: dev




---


spring:
  datasource:
    username: root
    password: amathon_password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://amathon-rds.c7jtzquabgo2.ap-southeast-1.rds.amazonaws.com:3306/amathon_db?useSSL=false&characterEncoding=utf8

---
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.connection.CharSet: utf8
      hibernate.connection.characterEncoding: utf8
      hibernate.connection.useUnicode: true
server:
  port: 8080
  servlet-path: /api


jsa:
  s3:
    bucket: amathonbucket

  aws:
    credentials:
      accessKey: AKIAJECLUXCH7VZZXMSQ
      secretKey: 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
