spring:


  datasource:
    username: root
    password: amathon_password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://amathon-rds.c7jtzquabgo2.ap-southeast-1.rds.amazonaws.com:3306/amathon_db?useSSL=false&characterEncoding=utf8


  jpa:
    database: mysql
    hibernate:
      ddl-auto: create

    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.connection.CharSet: utf8
      hibernate.connection.characterEncoding: utf8
      hibernate.connection.useUnicode: true

